import json
from datetime import datetime
from io import BytesIO
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer

class CBOMGenerator:
    @staticmethod
    def generate_json(assets: list):
        cbom = {
            "metadata": {
                "timestamp": datetime.now().isoformat(),
                "tool": "Q-Guardian v2.0",
                "format": "CycloneDX-Compatible"
            },
            "components": []
        }
        
        for asset in assets:
            cbom["components"].append({
                "name": asset["hostname"],
                "type": "service",
                "cryptography": {
                    "algorithm": asset["algorithm"],
                    "key_size": asset["key_size"],
                    "tls_version": asset["tls_version"],
                    "forward_secrecy": asset["forward_secrecy"]
                },
                "risk": {
                    "qtri_score": asset.get("qtri_score"),
                    "mosca_status": asset.get("mosca_risk_state")
                }
            })
        return cbom

    @staticmethod
    def export_pdf(assets: list):
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=landscape(A4), topMargin=30)
        elements = []
        styles = getSampleStyleSheet()
        
        # PNB Style
        pnb_maroon = colors.Color(165/255, 30/255, 54/255) # #A51E36 approx
        
        # Title
        styles.add(ParagraphStyle(name='PNBTitle', fontSize=18, textColor=pnb_maroon, spaceAfter=10, fontWeight='bold'))
        elements.append(Paragraph("Q-GUARDIAN | Cipher Bill of Materials (CBOM) Export", styles['PNBTitle']))
        elements.append(Paragraph(f"Organization: Punjab National Bank", styles['Normal']))
        elements.append(Paragraph(f"Export Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal']))
        elements.append(Spacer(1, 20))
        
        # Inventory Table
        elements.append(Paragraph("1. Cryptographic Inventory", styles['Heading2']))
        data = [["Hostname", "Algorithm", "Key Size", "TLS Version", "FS Enabled"]]
        for asset in assets:
            data.append([
                asset["hostname"],
                asset["algorithm"],
                str(asset["key_size"]),
                asset["tls_version"],
                "YES" if asset["forward_secrecy"] else "NO"
            ])
        
        t = Table(data, hAlign='LEFT', colWidths=[180, 100, 80, 80, 80])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), pnb_maroon),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.whitesmoke),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey)
        ]))
        elements.append(t)
        elements.append(Spacer(1, 25))
        
        # Risk Table
        elements.append(Paragraph("2. Risk Summary (QTRI & Mosca)", styles['Heading2']))
        risk_data = [["Hostname", "Sensitivity", "QTRI Score", "Mosca Risk State", "Policy Compliant"]]
        for asset in assets:
            # Reconstruct mosca data if it's a string from DB
            mosca = asset.get("mosca", {})
            if isinstance(mosca, str):
                try: mosca = json.loads(mosca)
                except: mosca = {}
                
            risk_data.append([
                asset["hostname"],
                asset["sensitivity_tier"],
                str(asset["qtri_score"]),
                mosca.get("risk_state", "N/A"),
                "YES" if asset["policy_compliant"] else "NO"
            ])
            
        rt = Table(risk_data, hAlign='LEFT', colWidths=[180, 80, 80, 100, 100])
        rt.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey)
        ]))
        elements.append(rt)
        
        # Footer
        elements.append(Spacer(1, 40))
        elements.append(Paragraph("Notes: This report is generated by Q-Guardian and aligns with NIST IR 8547 / CycloneDX 1.6 specifications.", styles['Italic']))
        elements.append(Paragraph("RESTRICTED: INTERNAL PNB SECURITY AUDIT DOCUMENT", styles['Normal']))
        
        doc.build(elements)
        buffer.seek(0)
        return buffer
